// This file contains a curated list of icons from different libraries.
// It's used by the CardNodeView to provide an icon picker.

export type IconLibrary = 'pi' | 'fa' | 'mi' | 'hi-solid' | 'hi-outline';

export interface Icon {
  key: string;
  name: string;
  library: IconLibrary;
  tags: string[];
}

// Helper to convert Heroicon names to our format
const heroiconName = (name: string, type: 'solid' | 'outline'): [string, string] => {
  const newName = name.replace(/Icon$/, '')
  const key = `hi-${newName.charAt(0).toLowerCase() + newName.slice(1)}-${type}`
  return [key, newName]
}

const pi = (key: string, name: string, tags: string[]): Icon => ({ key: `pi pi-${key}`, name, library: 'pi', tags })
const fa = (key: string, name: string, tags: string[]): Icon => ({ key: `fa fa-${key}`, name, library: 'fa', tags })
const mi = (key: string, name: string, tags: string[]): Icon => ({ key: `mi-${key}`, name, library: 'mi', tags })
const hiSolid = (name: string, tags: string[]): Icon => {
    const [key, newName] = heroiconName(name, 'solid')
    return { key, name: newName, library: 'hi-solid', tags }
}
const hiOutline = (name: string, tags: string[]): Icon => {
    const [key, newName] = heroiconName(name, 'outline')
    return { key, name: newName, library: 'hi-outline', tags }
}


export const allIcons: Icon[] = [
  // Prime Icons
  pi('bolt', 'Bolt', ['energy', 'fast', 'lightning']),
  pi('star', 'Star', ['favorite', 'rating', 'achievement']),
  pi('heart', 'Heart', ['love', 'like', 'favorite']),
  pi('check', 'Check', ['success', 'done', 'complete']),
  pi('info-circle', 'Info', ['information', 'details', 'help']),
  pi('exclamation-triangle', 'Warning', ['alert', 'error', 'danger']),
  pi('code', 'Code', ['development', 'programming', 'tech']),
  pi('database', 'Database', ['storage', 'data', 'server']),
  pi('server', 'Server', ['host', 'network', 'data']),
  pi('desktop', 'Desktop', ['computer', 'monitor', 'pc']),
  pi('mobile', 'Mobile', ['phone', 'device', 'tablet']),
  pi('cloud', 'Cloud', ['hosting', 'storage', 'server']),
  pi('briefcase', 'Briefcase', ['work', 'business', 'portfolio']),
  pi('chart-line', 'Chart', ['analytics', 'graph', 'stats']),
  pi('shopping-cart', 'Cart', ['ecommerce', 'store', 'buy']),
  pi('dollar', 'Dollar', ['money', 'finance', 'currency']),
  pi('calendar', 'Calendar', ['date', 'event', 'schedule']),
  pi('clock', 'Clock', ['time', 'hour', 'schedule']),
  pi('envelope', 'Email', ['mail', 'message', 'contact']),
  pi('comment', 'Comment', ['feedback', 'chat', 'discussion']),
  pi('bell', 'Bell', ['notification', 'alert', 'reminder']),
  pi('phone', 'Phone', ['call', 'contact', 'communication']),
  pi('send', 'Send', ['message', 'submit', 'dispatch']),
  pi('inbox', 'Inbox', ['email', 'messages', 'archive']),

  // Font Awesome
  fa('address-book', 'Address Book', ['contact', 'rolodex']),
  fa('anchor', 'Anchor', ['link', ' nautical', 'maritime']),
  fa('archive', 'Archive', ['box', 'storage', 'chest']),
  fa('area-chart', 'Area Chart', ['graph', 'analytics', 'statistics']),
  fa('at', 'At', ['email', 'address', 'handle']),
  fa('balance-scale', 'Balance Scale', ['justice', 'legal', 'measure']),
  fa('bank', 'Bank', ['institution', 'finance', 'building']),
  fa('bar-chart', 'Bar Chart', ['graph', 'analytics', 'statistics']),
  fa('barcode', 'Barcode', ['scan', 'product', 'upc']),
  fa('battery-full', 'Battery Full', ['power', 'charge', 'status']),
  fa('bed', 'Bed', ['hotel', 'sleep', 'rest']),
  fa('beer', 'Beer', ['alcohol', 'bar', 'drink']),
  fa('bicycle', 'Bicycle', ['bike', 'gears', 'transportation']),
  fa('birthday-cake', 'Birthday Cake', ['party', 'celebration', 'dessert']),
  fa('bluetooth', 'Bluetooth', ['wireless', 'connection', 'signal']),
  fa('bomb', 'Bomb', ['danger', 'explosion', 'error']),
  fa('book', 'Book', ['read', 'documentation', 'library']),
  fa('bookmark', 'Bookmark', ['save', 'favorite', 'remember']),
  fa('briefcase', 'Briefcase', ['work', 'business', 'office']),
  fa('bug', 'Bug', ['report', 'issue', 'error']),
  fa('building', 'Building', ['office', 'company', 'architecture']),
  fa('bullhorn', 'Bullhorn', ['announcement', 'share', 'broadcast']),
  fa('bus', 'Bus', ['vehicle', 'transportation', 'public']),
  fa('calculator', 'Calculator', ['math', 'numbers', 'arithmetic']),
  fa('camera-retro', 'Retro Camera', ['photo', 'picture', 'vintage']),
  fa('car', 'Car', ['vehicle', 'automobile', 'transportation']),
  fa('certificate', 'Certificate', ['badge', 'award', 'degree']),
  fa('coffee', 'Coffee', ['morning', 'mug', 'cafe']),
  fa('cog', 'Cog', ['settings', 'gear', 'options']),
  fa('cogs', 'Cogs', ['settings', 'gears', 'options']),
  fa('credit-card', 'Credit Card', ['payment', 'money', 'buy']),
  fa('crop', 'Crop', ['image', 'editing', 'design']),
  fa('cube', 'Cube', ['package', '3d', 'block']),
  fa('cubes', 'Cubes', ['packages', '3d', 'blocks']),
  fa('cutlery', 'Cutlery', ['food', 'restaurant', 'dining']),
  fa('dashboard', 'Dashboard', ['speedometer', 'admin', 'panel']),
  fa('diamond', 'Diamond', ['gem', 'jewelry', 'valuable']),
  fa('envelope-open', 'Open Envelope', ['email', 'mail', 'message']),
  fa('eraser', 'Eraser', ['delete', 'remove', 'edit']),
  fa('exchange', 'Exchange', ['transfer', 'arrows', 'swap']),
  fa('external-link', 'External Link', ['open', 'new', 'share']),
  fa('eye', 'Eye', ['view', 'see', 'visible']),
  fa('eye-slash', 'Eye Slash', ['hide', 'unview', 'hidden']),
  fa('fax', 'Fax', ['telecopy', 'office', 'machine']),
  fa('female', 'Female', ['woman', 'user', 'profile']),
  fa('fighter-jet', 'Fighter Jet', ['fly', 'plane', 'war']),
  fa('file-archive-o', 'Archive File', ['zip', 'compress', 'package']),
  fa('file-audio-o', 'Audio File', ['sound', 'music', 'mp3']),
  fa('file-code-o', 'Code File', ['html', 'css', 'js']),
  fa('file-excel-o', 'Excel File', ['spreadsheet', 'data', 'csv']),
  fa('file-image-o', 'Image File', ['photo', 'picture', 'jpg']),
  fa('file-pdf-o', 'PDF File', ['document', 'acrobat', 'export']),
  fa('file-powerpoint-o', 'PowerPoint File', ['presentation', 'slides', 'ppt']),
  fa('file-video-o', 'Video File', ['movie', 'recording', 'mp4']),
  fa('file-word-o', 'Word File', ['document', 'text', 'doc']),
  fa('film', 'Film', ['movie', 'video', 'cinema']),
  fa('filter', 'Filter', ['funnel', 'options', 'sort']),
  fa('fire', 'Fire', ['flame', 'hot', 'popular']),
  fa('flag', 'Flag', ['report', 'country', 'notice']),
  fa('flask', 'Flask', ['science', 'beaker', 'experiment']),
  fa('folder', 'Folder', ['directory', 'files', 'organization']),
  fa('folder-open', 'Open Folder', ['directory', 'files', 'load']),
  fa('gamepad', 'Gamepad', ['controller', 'play', 'video-game']),
  fa('gavel', 'Gavel', ['judge', 'law', 'legal']),
  fa('gift', 'Gift', ['present', 'box', 'celebration']),
  fa('glass', 'Glass', ['drink', 'bar', 'cheers']),
  fa('globe', 'Globe', ['world', 'planet', 'international']),
  fa('graduation-cap', 'Graduation Cap', ['learning', 'school', 'education']),
  fa('group', 'Group', ['users', 'people', 'team']),
  fa('handshake-o', 'Handshake', ['deal', 'agreement', 'greeting']),
  fa('hdd-o', 'HDD', ['hard-drive', 'storage', 'disk']),
  fa('headphones', 'Headphones', ['music', 'sound', 'audio']),
  fa('history', 'History', ['time', 'revert', 'archive']),
  fa('home', 'Home', ['main', 'house', 'dashboard']),
  fa('hourglass', 'Hourglass', ['time', 'loading', 'wait']),
  fa('id-card', 'ID Card', ['profile', 'user', 'identification']),
  fa('image', 'Image', ['photo', 'picture', 'art']),
  fa('industry', 'Industry', ['factory', 'manufacturing', 'building']),
  fa('key', 'Key', ['password', 'login', 'access']),
  fa('keyboard-o', 'Keyboard', ['typing', 'input', 'computer']),
  fa('language', 'Language', ['translate', 'international', 'speech']),
  fa('laptop', 'Laptop', ['computer', 'device', 'notebook']),
  fa('leaf', 'Leaf', ['eco', 'nature', 'green']),
  fa('legal', 'Legal', ['gavel', 'law', 'justice']),
  fa('lemon-o', 'Lemon', ['food', 'fruit', 'sour']),
  fa('level-down', 'Level Down', ['arrow', 'decrease', 'indent']),
  fa('level-up', 'Level Up', ['arrow', 'increase', 'unindent']),
  fa('life-ring', 'Life Ring', ['support', 'help', 'rescue']),
  fa('lightbulb-o', 'Lightbulb', ['idea', 'inspiration', 'tip']),
  fa('line-chart', 'Line Chart', ['graph', 'analytics', 'statistics']),
  fa('location-arrow', 'Location Arrow', ['map', 'gps', 'direction']),
  fa('lock', 'Lock', ['protect', 'security', 'password']),
  fa('magic', 'Magic', ['wizard', 'automatic', 'fantasy']),
  fa('magnet', 'Magnet', ['attract', 'tool', 'pull']),
  fa('male', 'Male', ['man', 'user', 'profile']),
  fa('map', 'Map', ['location', 'gps', 'travel']),
  fa('map-marker', 'Map Marker', ['pin', 'location', 'address']),
  fa('microphone', 'Microphone', ['record', 'voice', 'sound']),
  fa('microchip', 'Microchip', ['cpu', 'processor', 'tech']),
  fa('money', 'Money', ['cash', 'currency', 'payment']),
  fa('moon-o', 'Moon', ['night', 'dark', 'theme']),
  fa('motorcycle', 'Motorcycle', ['vehicle', 'bike', 'transportation']),
  fa('mouse-pointer', 'Mouse Pointer', ['cursor', 'select', 'click']),
  fa('music', 'Music', ['note', 'sound', 'song']),
  fa('newspaper-o', 'Newspaper', ['news', 'press', 'article']),
  fa('object-group', 'Object Group', ['design', 'combine', 'selection']),
  fa('object-ungroup', 'Object Ungroup', ['design', 'separate', 'selection']),
  fa('paint-brush', 'Paint Brush', ['design', 'art', 'color']),
  fa('paper-plane', 'Paper Plane', ['send', 'message', 'submit']),
  fa('paw', 'Paw', ['animal', 'pet', 'cat']),
  fa('pencil', 'Pencil', ['edit', 'write', 'update']),
  fa('percent', 'Percent', ['discount', 'rate', 'statistics']),
  fa('pie-chart', 'Pie Chart', ['graph', 'analytics', 'statistics']),
  fa('plane', 'Plane', ['fly', 'travel', 'airplane']),
  fa('plug', 'Plug', ['connect', 'power', 'electricity']),
  fa('power-off', 'Power Off', ['on', 'off', 'reboot']),
  fa('print', 'Print', ['paper', 'document', 'output']),
  fa('puzzle-piece', 'Puzzle Piece', ['addon', 'extension', 'module']),
  fa('qrcode', 'QR Code', ['scan', 'barcode', 'url']),
  fa('question-circle', 'Question Circle', ['help', 'info', 'support']),
  fa('quote-left', 'Quote Left', ['blockquote', 'citation', 'testimonial']),
  fa('quote-right', 'Quote Right', ['blockquote', 'citation', 'testimonial']),
  fa('random', 'Random', ['shuffle', 'sort', 'swap']),
  fa('recycle', 'Recycle', ['green', 'eco', 'trash']),
  fa('refresh', 'Refresh', ['reload', 'sync', 'update']),
  fa('reply', 'Reply', ['answer', 'respond', 'message']),
  fa('road', 'Road', ['street', 'travel', 'route']),
  fa('rocket', 'Rocket', ['launch', 'space', 'deploy']),
  fa('rss', 'RSS', ['feed', 'blog', 'subscribe']),
  fa('search', 'Search', ['find', 'lookup', 'magnify']),
  fa('share-alt', 'Share Alt', ['connect', 'social', 'network']),
  fa('shield', 'Shield', ['security', 'protect', 'defense']),
  fa('shopping-bag', 'Shopping Bag', ['buy', 'store', 'purchase']),
  fa('signal', 'Signal', ['wifi', 'connection', 'wireless']),
  fa('sitemap', 'Sitemap', ['hierarchy', 'organization', 'structure']),
  fa('sliders', 'Sliders', ['settings', 'options', 'controls']),
  fa('snowflake-o', 'Snowflake', ['winter', 'cold', 'frozen']),
  fa('sort', 'Sort', ['order', 'filter', 'arrange']),
  fa('space-shuttle', 'Space Shuttle', ['rocket', 'nasa', 'launch']),
  fa('spinner', 'Spinner', ['loading', 'progress', 'wait']),
  fa('spoon', 'Spoon', ['food', 'eat', 'utensil']),
  fa('square', 'Square', ['block', 'shape', 'box']),
  fa('star-half-o', 'Half Star', ['rating', 'review', 'favorite']),
  fa('star-o', 'Star Outline', ['rating', 'review', 'favorite']),
  fa('sticky-note', 'Sticky Note', ['message', 'reminder', 'todo']),
  fa('street-view', 'Street View', ['map', 'location', 'google']),
  fa('suitcase', 'Suitcase', ['travel', 'trip', 'luggage']),
  fa('sun-o', 'Sun', ['day', 'light', 'theme']),
  fa('support', 'Support', ['help', 'life-ring', 'question']),
  fa('tablet', 'Tablet', ['device', 'mobile', 'ipad']),
  fa('tag', 'Tag', ['label', 'category', 'keyword']),
  fa('tags', 'Tags', ['labels', 'categories', 'keywords']),
  fa('tasks', 'Tasks', ['checklist', 'todo', 'progress']),
  fa('taxi', 'Taxi', ['car', 'uber', 'vehicle']),
  fa('television', 'Television', ['tv', 'display', 'monitor']),
  fa('terminal', 'Terminal', ['code', 'command', 'console']),
  fa('thermometer-full', 'Thermometer', ['temperature', 'hot', 'fever']),
  fa('thumbs-down', 'Thumbs Down', ['dislike', 'reject', 'disapprove']),
  fa('thumbs-up', 'Thumbs Up', ['like', 'approve', 'favorite']),
  fa('ticket', 'Ticket', ['event', 'pass', 'support']),
  fa('toggle-off', 'Toggle Off', ['switch', 'inactive', 'off']),
  fa('toggle-on', 'Toggle On', ['switch', 'active', 'on']),
  fa('trademark', 'Trademark', ['copyright', 'brand', 'tm']),
  fa('trash', 'Trash', ['delete', 'remove', 'garbage']),
  fa('tree', 'Tree', ['nature', 'plant', 'eco']),
  fa('trophy', 'Trophy', ['award', 'winner', 'achievement']),
  fa('truck', 'Truck', ['delivery', 'shipping', 'vehicle']),
  fa('tty', 'TTY', ['accessibility', 'teletypewriter', 'deaf']),
  fa('umbrella', 'Umbrella', ['rain', 'weather', 'protection']),
  fa('university', 'University', ['college', 'education', 'school']),
  fa('unlock', 'Unlock', ['open', 'security', 'access']),
  fa('upload', 'Upload', ['import', 'publish', 'send']),
  fa('user', 'User', ['person', 'profile', 'account']),
  fa('user-circle', 'User Circle', ['person', 'profile', 'account']),
  fa('user-plus', 'Add User', ['invite', 'new', 'team']),
  fa('user-secret', 'Secret User', ['spy', 'incognito', 'private']),
  fa('user-times', 'Remove User', ['delete', 'disable', 'team']),
  fa('video-camera', 'Video Camera', ['record', 'movie', 'film']),
  fa('volume-down', 'Volume Down', ['audio', 'sound', 'lower']),
  fa('volume-up', 'Volume Up', ['audio', 'sound', 'higher']),
  fa('wheelchair', 'Wheelchair', ['accessibility', 'handicap', 'person']),
  fa('wifi', 'WiFi', ['wireless', 'internet', 'connection']),
  fa('wrench', 'Wrench', ['settings', 'tools', 'fix']),

  // Material Icons
  mi('ac_unit', 'AC Unit', ['cold', 'winter', 'snowflake']),
  mi('access_alarm', 'Alarm', ['clock', 'time', 'watch']),
  mi('accessibility', 'Accessibility', ['person', 'user', 'human']),
  mi('account_balance', 'Account Balance', ['bank', 'finance', 'money']),
  mi('account_circle', 'Account Circle', ['user', 'profile', 'person']),
  mi('add_shopping_cart', 'Add Shopping Cart', ['buy', 'store', 'ecommerce']),
  mi('add', 'Add', ['plus', 'create', 'new']),
  mi('agriculture', 'Agriculture', ['farm', 'tractor', 'nature']),
  mi('anchor', 'Anchor', ['ship', 'boat', 'sea']),
  mi('android', 'Android', ['logo', 'os', 'mobile']),
  mi('api', 'API', ['code', 'development', 'interface']),
  mi('architecture', 'Architecture', ['design', 'building', 'construction']),
  mi('archive', 'Archive', ['box', 'storage', 'inbox']),
  mi('assessment', 'Assessment', ['chart', 'graph', 'analytics']),
  mi('assignment', 'Assignment', ['clipboard', 'document', 'task']),
  mi('attachment', 'Attachment', ['file', 'paperclip', 'link']),
  mi('audiotrack', 'Audio Track', ['music', 'sound', 'note']),
  mi('auto_stories', 'Auto Stories', ['book', 'reading', 'library']),
  mi('backup', 'Backup', ['cloud', 'upload', 'storage']),
  mi('beach_access', 'Beach Access', ['umbrella', 'sand', 'summer']),
  mi('blender', 'Blender', ['cook', 'kitchen', 'food']),
  mi('bluetooth', 'Bluetooth', ['wireless', 'connection', 'signal']),
  mi('book', 'Book', ['reading', 'library', 'document']),
  mi('bookmark', 'Bookmark', ['save', 'favorite', 'remember']),
  mi('brush', 'Brush', ['paint', 'art', 'design']),
  mi('bug_report', 'Bug Report', ['issue', 'error', 'debug']),
  mi('build', 'Build', ['wrench', 'tool', 'construct']),
  mi('calculate', 'Calculate', ['math', 'numbers', 'calculator']),
  mi('camera_alt', 'Camera', ['photo', 'picture', 'image']),
  mi('campaign', 'Campaign', ['announcement', 'bullhorn', 'loud']),
  mi('carpenter', 'Carpenter', ['wood', 'tool', 'hammer']),
  mi('code', 'Code', ['development', 'programming', 'json']),
  mi('color_lens', 'Color Lens', ['palette', 'art', 'style']),
  mi('construction', 'Construction', ['wrench', 'hammer', 'tool']),
  mi('content_cut', 'Cut', ['scissors', 'edit', 'trim']),
  mi('content_paste', 'Paste', ['clipboard', 'document', 'copy']),
  mi('credit_card', 'Credit Card', ['payment', 'money', 'buy']),
  mi('crop', 'Crop', ['image', 'edit', 'frame']),
  mi('dangerous', 'Dangerous', ['warning', 'hazard', 'toxic']),
  mi('dashboard', 'Dashboard', ['panel', 'admin', 'speed']),
  mi('data_usage', 'Data Usage', ['chart', 'analytics', 'statistics']),
  mi('delete', 'Delete', ['trash', 'remove', 'garbage']),
  mi('dns', 'DNS', ['server', 'database', 'network']),
  mi('done', 'Done', ['check', 'tick', 'complete']),
  mi('dynamic_feed', 'Dynamic Feed', ['rss', 'posts', 'articles']),
  mi('eco', 'Eco', ['leaf', 'green', 'nature']),
  mi('edit', 'Edit', ['pencil', 'write', 'change']),
  mi('egg', 'Egg', ['food', 'breakfast', 'bird']),
  mi('eject', 'Eject', ['remove', 'media', 'player']),
  mi('engineering', 'Engineering', ['helmet', 'construction', 'worker']),
  mi('extension', 'Extension', ['puzzle', 'addon', 'module']),
  mi('face', 'Face', ['person', 'user', 'profile']),
  mi('favorite', 'Favorite', ['heart', 'love', 'like']),
  mi('feed', 'Feed', ['rss', 'article', 'news']),
  mi('file_download', 'Download', ['arrow', 'save', 'import']),
  mi('file_upload', 'Upload', ['arrow', 'send', 'export']),
  mi('filter_alt', 'Filter', ['funnel', 'options', 'sort']),
  mi('fingerprint', 'Fingerprint', ['security', 'id', 'biometric']),
  mi('fitness_center', 'Fitness Center', ['gym', 'dumbbell', 'workout']),
  mi('flag', 'Flag', ['country', 'report', 'goal']),
  mi('folder', 'Folder', ['directory', 'files', 'storage']),
  mi('functions', 'Functions', ['math', 'sigma', 'calculate']),
  mi('g_translate', 'Translate', ['language', 'google', 'text']),
  mi('gavel', 'Gavel', ['law', 'judge', 'legal']),
  mi('generating_tokens', 'Generating Tokens', ['ai', 'nlp', 'text']),
  mi('grade', 'Grade', ['star', 'rating', 'score']),
  mi('group_work', 'Group Work', ['team', 'collaboration', 'organization']),
  mi('headphones', 'Headphones', ['music', 'audio', 'sound']),
  mi('healing', 'Healing', ['health', 'bandage', 'medical']),
  mi('help', 'Help', ['question', 'support', 'info']),
  mi('history', 'History', ['time', 'revert', 'past']),
  mi('home', 'Home', ['house', 'main', 'start']),
  mi('html', 'HTML', ['code', 'web', 'development']),
  mi('http', 'HTTP', ['web', 'url', 'link']),
  mi('https', 'HTTPS', ['security', 'lock', 'web']),
  mi('hub', 'Hub', ['network', 'connect', 'share']),
  mi('image', 'Image', ['photo', 'picture', 'art']),
  mi('info', 'Info', ['information', 'details', 'about']),
  mi('javascript', 'Javascript', ['code', 'web', 'development']),
  mi('key', 'Key', ['password', 'access', 'lock']),
  mi('keyboard', 'Keyboard', ['input', 'typing', 'text']),
  mi('lan', 'LAN', ['network', 'server', 'connect']),
  mi('language', 'Language', ['world', 'globe', 'international']),
  mi('launch', 'Launch', ['external', 'open', 'new']),
  mi('layers', 'Layers', ['stack', 'design', 'arrange']),
  mi('leaderboard', 'Leaderboard', ['chart', 'stats', 'ranking']),
  mi('lightbulb', 'Lightbulb', ['idea', 'tip', 'inspiration']),
  mi('link', 'Link', ['url', 'chain', 'connect']),
  mi('list', 'List', ['bullet', 'items', 'todo']),
  mi('lock', 'Lock', ['security', 'password', 'protect']),
  mi('login', 'Login', ['signin', 'access', 'enter']),
  mi('logout', 'Logout', ['signout', 'exit', 'leave']),
  mi('loyalty', 'Loyalty', ['tag', 'price', 'sale']),
  mi('manage_accounts', 'Manage Accounts', ['user', 'settings', 'profile']),
  mi('memory', 'Memory', ['ram', 'chip', 'computer']),
  mi('model_training', 'Model Training', ['ai', 'brain', 'learn']),
  mi('mouse', 'Mouse', ['click', 'cursor', 'computer']),
  mi('movie', 'Movie', ['film', 'video', 'cinema']),
  mi('new_releases', 'New Releases', ['star', 'latest', 'update']),
  mi('notifications', 'Notifications', ['bell', 'alert', 'reminder']),
  mi('palette', 'Palette', ['color', 'design', 'art']),
  mi('pan_tool', 'Pan Tool', ['move', 'drag', 'hand']),
  mi('people', 'People', ['users', 'team', 'group']),
  mi('pets', 'Pets', ['paw', 'animal', 'dog']),
  mi('php', 'PHP', ['code', 'web', 'development']),
  mi('pie_chart', 'Pie Chart', ['graph', 'analytics', 'data']),
  mi('policy', 'Policy', ['security', 'shield', 'law']),
  mi('psychology', 'Psychology', ['brain', 'mind', 'thought']),
  mi('public', 'Public', ['globe', 'world', 'earth']),
  mi('push_pin', 'Push Pin', ['location', 'marker', 'save']),
  mi('recycling', 'Recycling', ['green', 'eco', 'trash']),
  mi('rocket_launch', 'Rocket Launch', ['space', 'deploy', 'ship']),
  mi('rss_feed', 'RSS Feed', ['blog', 'subscribe', 'news']),
  mi('rule', 'Rule', ['ruler', 'measure', 'design']),
  mi('savings', 'Savings', ['piggy-bank', 'money', 'finance']),
  mi('schedule', 'Schedule', ['clock', 'time', 'calendar']),
  mi('science', 'Science', ['flask', 'beaker', 'experiment']),
  mi('search', 'Search', ['find', 'magnify', 'lookup']),
  mi('security', 'Security', ['shield', 'lock', 'protect']),
  mi('segment', 'Segment', ['chart', 'data', 'analytics']),
  mi('send', 'Send', ['message', 'email', 'paper-plane']),
  mi('settings', 'Settings', ['cog', 'gear', 'options']),
  mi('share', 'Share', ['network', 'connect', 'social']),
  mi('shopping_cart', 'Shopping Cart', ['buy', 'ecommerce', 'store']),
  mi('smart_toy', 'Smart Toy', ['robot', 'ai', 'bot']),
  mi('source', 'Source', ['code', 'repository', 'github']),
  mi('sports_esports', 'Esports', ['gamepad', 'gaming', 'controller']),
  mi('storage', 'Storage', ['server', 'database', 'files']),
  mi('store', 'Store', ['shop', 'building', 'market']),
  mi('support', 'Support', ['life-ring', 'help', 'question']),
  mi('sync', 'Sync', ['refresh', 'reload', 'arrows']),
  mi('table_view', 'Table View', ['grid', 'rows', 'columns']),
  mi('task_alt', 'Task Alt', ['check', 'complete', 'done']),
  mi('terminal', 'Terminal', ['console', 'code', 'command']),
  mi('thumb_up', 'Thumb Up', ['like', 'approve', 'favorite']),
  mi('timeline', 'Timeline', ['graph', 'history', 'events']),
  mi('token', 'Token', ['key', 'badge', 'symbol']),
  mi('translate', 'Translate', ['language', 'text', 'words']),
  mi('trending_up', 'Trending Up', ['graph', 'analytics', 'increase']),
  mi('verified', 'Verified', ['check', 'badge', 'shield']),
  mi('visibility', 'Visibility', ['eye', 'see', 'view']),
  mi('webhook', 'Webhook', ['api', 'connect', 'data']),
  mi('work', 'Work', ['briefcase', 'office', 'business']),
  mi('workspaces', 'Workspaces', ['folders', 'groups', 'collaboration']),
  mi('youtube_searched_for', 'Youtube Searched For', ['video', 'play', 'media']),
  mi('zoom_in', 'Zoom In', ['magnify', 'increase', 'plus']),
  mi('zoom_out', 'Zoom Out', ['magnify', 'decrease', 'minus']),

  // Heroicons (Solid)
  hiSolid('AcademicCapIcon', ['education', 'school', 'learn']),
  hiSolid('AdjustmentsHorizontalIcon', ['settings', 'options', 'filters']),
  hiSolid('AdjustmentsVerticalIcon', ['settings', 'options', 'filters']),
  hiSolid('ArchiveBoxIcon', ['storage', 'files', 'mail']),
  hiSolid('ArrowDownTrayIcon', ['download', 'save', 'import']),
  hiSolid('ArrowUpTrayIcon', ['upload', 'send', 'export']),
  hiSolid('ArrowsPointingInIcon', ['minimize', 'collapse', 'shrink']),
  hiSolid('ArrowsPointingOutIcon', ['maximize', 'expand', 'fullscreen']),
  hiSolid('BackspaceIcon', ['delete', 'erase', 'remove']),
  hiSolid('BackwardIcon', ['rewind', 'previous', 'media']),
  hiSolid('BanknotesIcon', ['money', 'cash', 'currency']),
  hiSolid('Bars3Icon', ['menu', 'hamburger', 'navigation']),
  hiSolid('BeakerIcon', ['science', 'experiment', 'lab']),
  hiSolid('BellIcon', ['notification', 'alert', 'reminder']),
  hiSolid('BoltIcon', ['lightning', 'fast', 'energy']),
  hiSolid('BookOpenIcon', ['reading', 'documentation', 'learn']),
  hiSolid('BookmarkIcon', ['save', 'favorite', 'remember']),
  hiSolid('BriefcaseIcon', ['work', 'business', 'job']),
  hiSolid('BugAntIcon', ['error', 'issue', 'debug']),
  hiSolid('BuildingOfficeIcon', ['company', 'work', 'place']),
  hiSolid('CalculatorIcon', ['math', 'numbers', 'tally']),
  hiSolid('CalendarDaysIcon', ['date', 'event', 'schedule']),
  hiSolid('ChartBarIcon', ['graph', 'statistics', 'analytics']),
  hiSolid('ChartPieIcon', ['graph', 'statistics', 'analytics']),
  hiSolid('ChatBubbleLeftRightIcon', ['communication', 'talk', 'message']),
  hiSolid('CheckBadgeIcon', ['verified', 'success', 'award']),
  hiSolid('ChevronDownIcon', ['arrow', 'expand', 'more']),
  hiSolid('ChevronUpIcon', ['arrow', 'collapse', 'less']),
  hiSolid('CircleStackIcon', ['database', 'storage', 'server']),
  hiSolid('ClipboardDocumentCheckIcon', ['task', 'done', 'report']),
  hiSolid('ClockIcon', ['time', 'hour', 'schedule']),
  hiSolid('CloudIcon', ['weather', 'storage', 'network']),
  hiSolid('CodeBracketIcon', ['development', 'programming', 'embed']),
  hiSolid('Cog6ToothIcon', ['settings', 'options', 'gear']),
  hiSolid('CommandLineIcon', ['terminal', 'console', 'code']),
  hiSolid('ComputerDesktopIcon', ['pc', 'monitor', 'machine']),
  hiSolid('CpuChipIcon', ['processor', 'tech', 'hardware']),
  hiSolid('CreditCardIcon', ['payment', 'money', 'buy']),
  hiSolid('CubeIcon', ['package', '3d', 'block']),
  hiSolid('CurrencyDollarIcon', ['money', 'finance', 'cash']),
  hiSolid('DevicePhoneMobileIcon', ['smartphone', 'cell', 'call']),
  hiSolid('DeviceTabletIcon', ['ipad', 'mobile', 'screen']),
  hiSolid('DocumentDuplicateIcon', ['copy', 'clone', 'files']),
  hiSolid('DocumentIcon', ['file', 'page', 'text']),
  hiSolid('EllipsisHorizontalIcon', ['more', 'options', 'dots']),
  hiSolid('EnvelopeIcon', ['email', 'mail', 'message']),
  hiSolid('ExclamationTriangleIcon', ['warning', 'alert', 'danger']),
  hiSolid('EyeIcon', ['view', 'visible', 'see']),
  hiSolid('EyeSlashIcon', ['hidden', 'unview', 'hide']),
  hiSolid('FilmIcon', ['movie', 'video', 'cinema']),
  hiSolid('FingerPrintIcon', ['security', 'id', 'biometric']),
  hiSolid('FlagIcon', ['report', 'mark', 'country']),
  hiSolid('FolderIcon', ['directory', 'files', 'storage']),
  hiSolid('ForwardIcon', ['fast-forward', 'next', 'media']),
  hiSolid('FunnelIcon', ['filter', 'sort', 'options']),
  hiSolid('GifIcon', ['image', 'animation', 'file']),
  hiSolid('GiftIcon', ['present', 'package', 'reward']),
  hiSolid('GlobeAltIcon', ['world', 'international', 'language']),
  hiSolid('HandThumbDownIcon', ['dislike', 'reject', 'no']),
  hiSolid('HandThumbUpIcon', ['like', 'approve', 'yes']),
  hiSolid('HashtagIcon', ['tag', 'topic', 'social']),
  hiSolid('HeartIcon', ['love', 'favorite', 'like']),
  hiSolid('HomeIcon', ['house', 'main', 'start']),
  hiSolid('IdentificationIcon', ['id', 'user', 'profile']),
  hiSolid('InboxIcon', ['mail', 'messages', 'storage']),
  hiSolid('InformationCircleIcon', ['help', 'details', 'about']),
  hiSolid('KeyIcon', ['password', 'access', 'login']),
  hiSolid('LanguageIcon', ['translate', 'international', 'speech']),
  hiSolid('LifebuoyIcon', ['support', 'help', 'rescue']),
  hiSolid('LightBulbIcon', ['idea', 'tip', 'inspiration']),
  hiSolid('LinkIcon', ['url', 'chain', 'connect']),
  hiSolid('LockClosedIcon', ['security', 'protect', 'password']),
  hiSolid('LockOpenIcon', ['unlocked', 'access', 'public']),
  hiSolid('MagnifyingGlassIcon', ['search', 'find', 'lookup']),
  hiSolid('MapPinIcon', ['location', 'marker', 'address']),
  hiSolid('MegaphoneIcon', ['announcement', 'broadcast', 'share']),
  hiSolid('MicrophoneIcon', ['record', 'voice', 'audio']),
  hiSolid('MinusCircleIcon', ['remove', 'delete', 'subtract']),
  hiSolid('MusicalNoteIcon', ['sound', 'song', 'audio']),
  hiSolid('NewspaperIcon', ['news', 'article', 'press']),
  hiSolid('PaintBrushIcon', ['design', 'art', 'color']),
  hiSolid('PaperAirplaneIcon', ['send', 'submit', 'message']),
  hiSolid('PaperClipIcon', ['attachment', 'file', 'link']),
  hiSolid('PauseIcon', ['stop', 'hold', 'media']),
  hiSolid('PencilIcon', ['edit', 'write', 'update']),
  hiSolid('PhoneIcon', ['call', 'contact', 'talk']),
  hiSolid('PhotoIcon', ['image', 'picture', 'art']),
  hiSolid('PlayIcon', ['start', 'run', 'media']),
  hiSolid('PlusCircleIcon', ['add', 'new', 'create']),
  hiSolid('PresentationChartLineIcon', ['analytics', 'graph', 'report']),
  hiSolid('PrinterIcon', ['print', 'output', 'document']),
  hiSolid('PuzzlePieceIcon', ['addon', 'extension', 'module']),
  hiSolid('QrCodeIcon', ['scan', 'barcode', 'url']),
  hiSolid('QuestionMarkCircleIcon', ['help', 'support', 'info']),
  hiSolid('RocketLaunchIcon', ['deploy', 'space', 'release']),
  hiSolid('RssIcon', ['feed', 'blog', 'subscribe']),
  hiSolid('ScaleIcon', ['balance', 'law', 'justice']),
  hiSolid('ScissorsIcon', ['cut', 'trim', 'edit']),
  hiSolid('ServerStackIcon', ['database', 'storage', 'network']),
  hiSolid('ShareIcon', ['social', 'connect', 'network']),
  hiSolid('ShieldCheckIcon', ['security', 'verified', 'protect']),
  hiSolid('ShoppingCartIcon', ['buy', 'ecommerce', 'store']),
  hiSolid('SparklesIcon', ['magic', 'ai', 'new']),
  hiSolid('SpeakerWaveIcon', ['volume', 'sound', 'audio']),
  hiSolid('Square2StackIcon', ['copy', 'duplicate', 'clone']),
  hiSolid('StarIcon', ['favorite', 'rating', 'achievement']),
  hiSolid('StopIcon', ['end', 'cancel', 'media']),
  hiSolid('SunIcon', ['light', 'day', 'theme']),
  hiSolid('TableCellsIcon', ['grid', 'data', 'spreadsheet']),
  hiSolid('TagIcon', ['label', 'category', 'keyword']),
  hiSolid('TrashIcon', ['delete', 'remove', 'garbage']),
  hiSolid('TrophyIcon', ['award', 'achievement', 'winner']),
  hiSolid('TvIcon', ['television', 'display', 'monitor']),
  hiSolid('UserCircleIcon', ['profile', 'person', 'account']),
  hiSolid('UserGroupIcon', ['team', 'people', 'collaboration']),
  hiSolid('UserIcon', ['person', 'profile', 'account']),
  hiSolid('VideoCameraIcon', ['record', 'movie', 'film']),
  hiSolid('WalletIcon', ['money', 'finance', 'cash']),
  hiSolid('WifiIcon', ['internet', 'connection', 'wireless']),
  hiSolid('WindowIcon', ['app', 'browser', 'display']),
  hiSolid('WrenchScrewdriverIcon', ['tools', 'settings', 'fix']),
  hiSolid('XCircleIcon', ['cancel', 'close', 'error']),
  hiSolid('XMarkIcon', ['close', 'cancel', 'remove']),

  // Heroicons (Outline)
  hiOutline('AcademicCapIcon', ['education', 'school', 'learn']),
  hiOutline('AdjustmentsHorizontalIcon', ['settings', 'options', 'filters']),
  hiOutline('AdjustmentsVerticalIcon', ['settings', 'options', 'filters']),
  hiOutline('ArchiveBoxIcon', ['storage', 'files', 'mail']),
  hiOutline('ArrowDownTrayIcon', ['download', 'save', 'import']),
  hiOutline('ArrowUpTrayIcon', ['upload', 'send', 'export']),
  hiOutline('BackspaceIcon', ['delete', 'erase', 'remove']),
  hiOutline('BanknotesIcon', ['money', 'cash', 'currency']),
  hiOutline('Bars3Icon', ['menu', 'hamburger', 'navigation']),
  hiOutline('BeakerIcon', ['science', 'experiment', 'lab']),
  hiOutline('BellIcon', ['notification', 'alert', 'reminder']),
  hiOutline('BoltIcon', ['lightning', 'fast', 'energy']),
  hiOutline('BookOpenIcon', ['reading', 'documentation', 'learn']),
  hiOutline('BookmarkIcon', ['save', 'favorite', 'remember']),
  hiOutline('BriefcaseIcon', ['work', 'business', 'job']),
  hiOutline('BugAntIcon', ['error', 'issue', 'debug']),
  hiOutline('BuildingOfficeIcon', ['company', 'work', 'place']),
  hiOutline('CalculatorIcon', ['math', 'numbers', 'tally']),
  hiOutline('CalendarDaysIcon', ['date', 'event', 'schedule']),
  hiOutline('ChartBarIcon', ['graph', 'statistics', 'analytics']),
  hiOutline('ChatBubbleLeftRightIcon', ['communication', 'talk', 'message']),
  hiOutline('CheckBadgeIcon', ['verified', 'success', 'award']),
  hiOutline('CircleStackIcon', ['database', 'storage', 'server']),
  hiOutline('ClipboardDocumentCheckIcon', ['task', 'done', 'report']),
  hiOutline('ClockIcon', ['time', 'hour', 'schedule']),
  hiOutline('CloudIcon', ['weather', 'storage', 'network']),
  hiOutline('CodeBracketIcon', ['development', 'programming', 'embed']),
  hiOutline('Cog6ToothIcon', ['settings', 'options', 'gear']),
  hiOutline('CommandLineIcon', ['terminal', 'console', 'code']),
  hiOutline('ComputerDesktopIcon', ['pc', 'monitor', 'machine']),
  hiOutline('CpuChipIcon', ['processor', 'tech', 'hardware']),
  hiOutline('CreditCardIcon', ['payment', 'money', 'buy']),
  hiOutline('CubeIcon', ['package', '3d', 'block']),
  hiOutline('DevicePhoneMobileIcon', ['smartphone', 'cell', 'call']),
  hiOutline('DocumentDuplicateIcon', ['copy', 'clone', 'files']),
  hiOutline('EnvelopeIcon', ['email', 'mail', 'message']),
  hiOutline('ExclamationTriangleIcon', ['warning', 'alert', 'danger']),
  hiOutline('EyeIcon', ['view', 'visible', 'see']),
  hiOutline('FilmIcon', ['movie', 'video', 'cinema']),
  hiOutline('FingerPrintIcon', ['security', 'id', 'biometric']),
  hiOutline('FlagIcon', ['report', 'mark', 'country']),
  hiOutline('FolderIcon', ['directory', 'files', 'storage']),
  hiOutline('FunnelIcon', ['filter', 'sort', 'options']),
  hiOutline('GiftIcon', ['present', 'package', 'reward']),
  hiOutline('GlobeAltIcon', ['world', 'international', 'language']),
  hiOutline('HandThumbUpIcon', ['like', 'approve', 'yes']),
  hiOutline('HeartIcon', ['love', 'favorite', 'like']),
  hiOutline('HomeIcon', ['house', 'main', 'start']),
  hiOutline('InformationCircleIcon', ['help', 'details', 'about']),
  hiOutline('KeyIcon', ['password', 'access', 'login']),
  hiOutline('LanguageIcon', ['translate', 'international', 'speech']),
  hiOutline('LifebuoyIcon', ['support', 'help', 'rescue']),
  hiOutline('LightBulbIcon', ['idea', 'tip', 'inspiration']),
  hiOutline('LinkIcon', ['url', 'chain', 'connect']),
  hiOutline('LockClosedIcon', ['security', 'protect', 'password']),
  hiOutline('MagnifyingGlassIcon', ['search', 'find', 'lookup']),
  hiOutline('MapPinIcon', ['location', 'marker', 'address']),
  hiOutline('MegaphoneIcon', ['announcement', 'broadcast', 'share']),
  hiOutline('MicrophoneIcon', ['record', 'voice', 'audio']),
  hiOutline('NewspaperIcon', ['news', 'article', 'press']),
  hiOutline('PaintBrushIcon', ['design', 'art', 'color']),
  hiOutline('PaperAirplaneIcon', ['send', 'submit', 'message']),
  hiOutline('PencilIcon', ['edit', 'write', 'update']),
  hiOutline('PhoneIcon', ['call', 'contact', 'talk']),
  hiOutline('PhotoIcon', ['image', 'picture', 'art']),
  hiOutline('PresentationChartLineIcon', ['analytics', 'graph', 'report']),
  hiOutline('PrinterIcon', ['print', 'output', 'document']),
  hiOutline('PuzzlePieceIcon', ['addon', 'extension', 'module']),
  hiOutline('QrCodeIcon', ['scan', 'barcode', 'url']),
  hiOutline('QuestionMarkCircleIcon', ['help', 'support', 'info']),
  hiOutline('RocketLaunchIcon', ['deploy', 'space', 'release']),
  hiOutline('ShareIcon', ['social', 'connect', 'network']),
  hiOutline('ShieldCheckIcon', ['security', 'verified', 'protect']),
  hiOutline('ShoppingCartIcon', ['buy', 'ecommerce', 'store']),
  hiOutline('SparklesIcon', ['magic', 'ai', 'new']),
  hiOutline('StarIcon', ['favorite', 'rating', 'achievement']),
  hiOutline('SunIcon', ['light', 'day', 'theme']),
  hiOutline('TagIcon', ['label', 'category', 'keyword']),
  hiOutline('TrashIcon', ['delete', 'remove', 'garbage']),
  hiOutline('TrophyIcon', ['award', 'achievement', 'winner']),
  hiOutline('UserCircleIcon', ['profile', 'person', 'account']),
  hiOutline('UserGroupIcon', ['team', 'people', 'collaboration']),
  hiOutline('WifiIcon', ['internet', 'connection', 'wireless']),
  hiOutline('WrenchScrewdriverIcon', ['tools', 'settings', 'fix']),
]
